#! /bin/sh

# .tex & .cls file must have the same name!
if [ -z "$1" ]; then
	printf "filename: "
	read filename
else
	filename="$1"
fi

ls "$filename.tex" "$filename.cls" \
	| entr -s "pdflatex -interaction nonstopmode -shell-escape -file-line-error $filename.tex"
